# This is a basic workflow to help you get started with Actions

name: CI-Lavoz-Web

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
            SSH_PRIVATE_KEY: ${{ secrets.PUBLIC_DEVELOP }}
            REMOTE_HOST: 35.239.48.152
            REMOTE_USER: pedro
            TARGET: /home/pedro/ale
      - name: Comandos deploy
        uses: appleboy/ssh-action@master
        with:
          host: 35.239.48.152
          username: pedro
          key: ${{ secrets.PUBLIC_DEVELOP }}
          port: 22
          script: |
            cd /home/pedro/ale/
            docker-compose down
            docker-compose build
            docker-compose up -d
            docker-compose exec php bash -c "npm update"
            docker-compose exec php bash -c "npm run prod"
            docker-compose exec php bash -c "php artisan cache:clear"
            ls -l
