# This is a basic workflow to help you get started with Actions

name: CI-Lavoz-Web

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ ci ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone and checkout actual branch
        uses: actions/checkout@v2
      - name: ssh deploy
        uses: appleboy/ssh-action@master
        with:
          host: 104.155.137.39
          username: pedro
          key: ${{ secrets.DEPLOY_SECRET }}
          port: 22
          script: |
            cd /home/agustinpereyra_e/sooft/LaVoz-WyleexAnalytics-Web
            docker-compose build
            docker-compose up -d
            docker-compose exec -T php bash -c "npm update"
            docker-compose exec -T php bash -c "npm run prod"
            #docker-compose exec -T php bash -c "composer update"   
